
CREATE TABLE IF NOT EXISTS  "friend" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "following_user_id" integer,
  "followed_user_id" integer,
  "is_accept" boolean,
  "is_active" boolean
);

CREATE TABLE IF NOT EXISTS  "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar,
  "name" varchar,
  "email" varchar,
  "birthday" date,
  "is_active" boolean
);

CREATE TABLE IF NOT EXISTS  "film" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "release_date" date,
  "duration" integer,
  "rate_mpa_id" integer,
  "is_active" boolean
);

CREATE TABLE IF NOT EXISTS  "like" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "film_id" integer,
  "user_id" integer,
  "is_active" boolean
);

CREATE TABLE IF NOT EXISTS  "genre" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "is_active" boolean
);

CREATE TABLE IF NOT EXISTS  "film_genre" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "film_id" integer,
  "genre_id" integer,
  "is_active" boolean
);

CREATE TABLE IF NOT EXISTS  "rate_mpa" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "is_active" boolean
);

ALTER TABLE "like" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "friend" ADD FOREIGN KEY ("following_user_id") REFERENCES "user" ("id");

ALTER TABLE "friend" ADD FOREIGN KEY ("followed_user_id") REFERENCES "user" ("id");

ALTER TABLE "like" ADD FOREIGN KEY ("film_id") REFERENCES "film" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("film_id") REFERENCES "film" ("id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");

ALTER TABLE "film" ADD FOREIGN KEY ("rate_mpa_id") REFERENCES "rate_mpa" ("id");